In [1]:
from fastai.text import * 
from fastai.callbacks import *
from sklearn.model_selection import train_test_split
from pathlib import Path
import pickle as pkl

torch.cuda.set_device(0)

In [2]:
import unicodedata
import pandas as pd
import re
import spacy
import json

In [3]:
PATH = Path('.')

In [4]:
def normalize_title(title):
    s = re.sub(r'[^a-zA-Z0-9ñç% ]', ' ', unicodedata.normalize('NFKD', title.lower()).encode('ascii', 'ignore').decode("utf-8"))
#    s = re.sub(r'[\d]+', "1", s)
    s = re.sub(r's |s$', ' ', s)
    s = re.sub(r' +', ' ', s)
    s = re.sub(r'(1 )+', '1 ', s)
    return re.sub(r'o |o$', 'a ', s).strip()

In [5]:
with open("main_categories.json", "r") as f:
    cats = json.load(f)

In [6]:
df = pd.read_csv(PATH / 'test.csv')

In [7]:
d = df[df.language == 'portuguese']

In [8]:
d.title = d.title.apply(normalize_title)

/home/jdg/miniconda3/envs/fastai/lib/python3.7/site-packages/pandas/core/generic.py:5096: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [9]:
config = awd_lstm_clas_config.copy()
config['qrnn'] = True
config['n_hid'] = 1550 #default 1152
config['n_layers'] = 4 #default 3

In [30]:
processor = SPProcessor.load('',tmp_dir='lm_por_v4')

In [31]:
learn_c = load_learner('/data/anime/ml/', 'classifier_por_v4_3_export', test=d.title)

In [32]:
learn_c.predict('Espelho Veneziano Oval Decorativo Retro Vintage Antigo')

(Category Casa, Moveis e Decoracao,
 tensor(12),
 tensor([2.1547e-02, 1.3029e-02, 5.2541e-03, 5.2216e-03, 7.9526e-03, 1.8766e-02,
         4.9096e-03, 2.6168e-03, 6.4986e-03, 8.1903e-03, 6.9419e-03, 1.5970e-04,
         6.4891e-01, 3.9271e-03, 1.2811e-02, 3.1353e-02, 2.7254e-02, 2.1493e-02,
         3.6358e-02, 1.0258e-03, 8.5602e-03, 9.8066e-04, 6.9761e-03, 6.8136e-02,
         1.5370e-02, 7.8588e-03, 3.2253e-03, 4.6769e-03]))

In [13]:
learn_c.data.show_batch(ds_type=DatasetType.Test, rows=10)

In [14]:
probs = learn_c.get_preds(ds_type=DatasetType.Test, ordered=True)
pred_indices = torch.argmax(probs[0], dim=1)
preds_clas = [learn_c.data.classes[pred] for pred in pred_indices]

In [15]:
learn_c.predict('Kit Maternidade Bolsa-mala Baby/bebe Vinho Menina Kb2012')

(Category Bebes,
 tensor(6),
 tensor([1.8512e-04, 7.2365e-04, 2.7802e-04, 3.3792e-04, 7.0403e-05, 2.6059e-03,
         9.7006e-01, 4.7331e-03, 2.1817e-03, 1.2976e-02, 2.8844e-04, 8.6983e-06,
         1.1978e-03, 1.0801e-04, 1.6061e-04, 2.3147e-04, 7.0266e-04, 4.7184e-04,
         1.0991e-03, 3.8454e-05, 1.1170e-04, 4.6863e-05, 1.1915e-04, 6.5400e-05,
         9.7976e-05, 2.2262e-04, 2.7752e-05, 8.4527e-04]))

In [16]:
probs[0][0]

tensor([8.4734e-05, 5.3279e-04, 1.3279e-04, 1.9145e-05, 1.0313e-05, 6.5441e-04,
        9.8840e-01, 4.0189e-04, 2.3794e-04, 8.3081e-03, 1.8368e-05, 1.2278e-06,
        3.1116e-04, 4.3357e-05, 2.8517e-05, 6.3742e-05, 1.2342e-04, 1.1039e-04,
        2.6298e-04, 1.0569e-05, 3.3712e-05, 1.3677e-05, 2.2649e-05, 1.8131e-05,
        1.8214e-05, 3.8575e-05, 4.8017e-06, 9.4040e-05])

In [17]:
df.loc[df.language == 'portuguese', 'main_category'] = preds_clas

In [18]:
for cat in set(cats.values()):
    learn_c = load_learner('/data/anime/ml/por/', cat + '_model_export', test = df[(df.language == 'portuguese') & (df.main_category == cat)])
    probs = learn_c.get_preds(ds_type=DatasetType.Test, ordered=True)
    pred_indices = torch.argmax(probs[0], dim=1)
    preds_clas = [learn_c.data.classes[pred] for pred in pred_indices]
    df.loc[(df.language == 'portuguese') & (df.main_category == cat), 'category'] = preds_clas

In [19]:
df

id                                              title    language  \
0            0  Kit Maternidade Bolsa-mala Baby/bebe Vinho Men...  portuguese   
1            1  Trocador De Fraldas Fisher Price Feminino Rosa...  portuguese   
2            2  Motor Ventoinha - Fiat Idea / Palio 1.8 - A 04...  portuguese   
3            3  Amortecedor Mola Batente D Dir New Civic 14 - ...  portuguese   
4            4  Cadeirinha De Carro Bebê Princesa Princess 9 A...  portuguese   
5            5  Cabo Freio Mao Tras Direito Vw Up Cod 1s060972...  portuguese   
6            6  Mini Pc Dell Optiplex Fx160 Atom 2gb Ram Ssd 1...  portuguese   
7            7                      Kit Bi Xenon Lâmpada H4 8000k  portuguese   
8            8  Protetor Pé Botinha-kickboxing Karate Taekwond...  portuguese   
9            9  Disco Rigido Externo Western Digital Elements ...     spanish   
10          10             Picadora De Carne Fineschi Legitima 32     spanish   
11          11  Saída Maternidade 1 Manta 2vestidos 2calças +b...  portuguese   
12          12  Jogo Vela Ignicao Ngk Mercedes Benz 08/11 Clc ...  portuguese   
13          13      Modulo De Injeção Fox Flex 1.6 032 906 032 Aa  portuguese   
14          14  Set Barreta Automotor Bremen X3 Unid. 6756 20 ...     spanish   
15          15                   Miel Organica X250gr. (sin Tacc)     spanish   
16          16                                Sax Tenor Coon 37m   portuguese   
17          17  Sapato Seguranca Vaqueta Bidensidade Com Bique...  portuguese   
18          18  200 Adaptador Para Cartão De Memória Micro Sd ...  portuguese   
19          19               Bandeja Giradiscos Omnitronic Bd1320     spanish   
20          20                                      Tonfa Militar  portuguese   
21          21  Kit Almohadones Y Funda 2 Respaldos + 2 Carame...     spanish   
22          22  Parlante Portatil Hp Mini Roar Bluetooth 2,5w ...     spanish   
23          23  Tubos Pelotas Slazenger Wimbledon - Promo Enví...     spanish   
24          24  Sapata De Freio (jg) Escort Zetec 1.8 16v 97/....  portuguese   
25          25  Ukelele Electroacustico Baritono Alpujarra Tub...     spanish   
26          26  Aire Split Frio Calor 5332f / 6200w Fedders Ms...     spanish   
27          27  Piedritas Sanitarias Stone Cat X 24kg ¡¡ Aglom...     spanish   
28          28         Arte De Bordar N 5 Alfabetos Em Ponto Cruz  portuguese   
29          29  Mascara Fotosensible Careta Soldar Ploteo Fueg...     spanish   
...        ...                                                ...         ...   
246925  246925                    Bota Industrial Calfor Pampeana     spanish   
246926  246926  Vestido Novia Importado En Encaje Y Chiffon Bl...     spanish   
246927  246927                         Paralama Direito Polo 2008  portuguese   
246928  246928  Indio Gigante Ovos Galados/ferteis A Nossa Duz...  portuguese   
246929  246929  Kit 36 Canudo Longo De Vidro Reutilizável Reto...  portuguese   
246930  246930  Silla Mecedora Bebe Con Vibracion Sonido Jugue...     spanish   
246931  246931  Par Lâmpada Philips Led Fog Ultinon 6200k H8 H...  portuguese   
246932  246932  Inalador Nebulizador Ultrassônico Portatil Pro...  portuguese   
246933  246933  Cinta Correctora Estilo De La Pluma, De Líneas...     spanish   
246934  246934                        Tanque Nafta Corsa Clasicc      spanish   
246935  246935    Contrabaixo Strinberg Cab16 - 4 Cordas Sunburst  portuguese   
246936  246936                 Muy Linda Cinta Athletic A Reparar     spanish   
246937  246937          Portalampara Con Chicote Pack 10 Unidades     spanish   
246938  246938     Revista Formula 1 F1 50 Anos Dourados Raridade  portuguese   
246939  246939     Kit De Bixenon H4 12v 8000k Hid Xenon Kith4-8k     spanish   
246940  246940  Solia De Viraró Seco De Horno De 12mm. De Espesor     spanish   
246941  246941                           Ena Shaker Premium Vaso      spanish   
246942  246942  Interruptor Vidro Traseiro 

In [20]:
d = df[df.language == 'spanish']

In [21]:
d.title = d.title.apply(normalize_title)

/home/jdg/miniconda3/envs/fastai/lib/python3.7/site-packages/pandas/core/generic.py:5096: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


In [22]:
processor = SPProcessor.load('',tmp_dir='lm_es_v4')

In [23]:
learn_c = load_learner('/data/anime/ml/', 'classifier_es_v4_3_export', test=d.title)

In [24]:
learn_c.data.show_batch(ds_type=DatasetType.Test, rows=10)

In [25]:
probs = learn_c.get_preds(ds_type=DatasetType.Test, ordered=True)
pred_indices = torch.argmax(probs[0], dim=1)
preds_clas = [learn_c.data.classes[pred] for pred in pred_indices]

In [26]:
df.loc[df.language == 'spanish', 'main_category'] = preds_clas

In [27]:
for cat in set(cats.values()):
    learn_c = load_learner('/data/anime/ml/es/', cat + '_model_export', test = df[(df.language == 'spanish') & (df.main_category == cat)])
    probs = learn_c.get_preds(ds_type=DatasetType.Test, ordered=True)
    pred_indices = torch.argmax(probs[0], dim=1)
    preds_clas = [learn_c.data.classes[pred] for pred in pred_indices]
    df.loc[(df.language == 'spanish') & (df.main_category == cat), 'category'] = preds_clas

In [28]:
d2 = df.copy()
d2.pop('main_category')
d2.pop('title')
d2.pop('language')
d2.to_csv('submission2.csv', index=False)

In [29]:
df

id                                              title    language  \
0            0  Kit Maternidade Bolsa-mala Baby/bebe Vinho Men...  portuguese   
1            1  Trocador De Fraldas Fisher Price Feminino Rosa...  portuguese   
2            2  Motor Ventoinha - Fiat Idea / Palio 1.8 - A 04...  portuguese   
3            3  Amortecedor Mola Batente D Dir New Civic 14 - ...  portuguese   
4            4  Cadeirinha De Carro Bebê Princesa Princess 9 A...  portuguese   
5            5  Cabo Freio Mao Tras Direito Vw Up Cod 1s060972...  portuguese   
6            6  Mini Pc Dell Optiplex Fx160 Atom 2gb Ram Ssd 1...  portuguese   
7            7                      Kit Bi Xenon Lâmpada H4 8000k  portuguese   
8            8  Protetor Pé Botinha-kickboxing Karate Taekwond...  portuguese   
9            9  Disco Rigido Externo Western Digital Elements ...     spanish   
10          10             Picadora De Carne Fineschi Legitima 32     spanish   
11          11  Saída Maternidade 1 Manta 2vestidos 2calças +b...  portuguese   
12          12  Jogo Vela Ignicao Ngk Mercedes Benz 08/11 Clc ...  portuguese   
13          13      Modulo De Injeção Fox Flex 1.6 032 906 032 Aa  portuguese   
14          14  Set Barreta Automotor Bremen X3 Unid. 6756 20 ...     spanish   
15          15                   Miel Organica X250gr. (sin Tacc)     spanish   
16          16                                Sax Tenor Coon 37m   portuguese   
17          17  Sapato Seguranca Vaqueta Bidensidade Com Bique...  portuguese   
18          18  200 Adaptador Para Cartão De Memória Micro Sd ...  portuguese   
19          19               Bandeja Giradiscos Omnitronic Bd1320     spanish   
20          20                                      Tonfa Militar  portuguese   
21          21  Kit Almohadones Y Funda 2 Respaldos + 2 Carame...     spanish   
22          22  Parlante Portatil Hp Mini Roar Bluetooth 2,5w ...     spanish   
23          23  Tubos Pelotas Slazenger Wimbledon - Promo Enví...     spanish   
24          24  Sapata De Freio (jg) Escort Zetec 1.8 16v 97/....  portuguese   
25          25  Ukelele Electroacustico Baritono Alpujarra Tub...     spanish   
26          26  Aire Split Frio Calor 5332f / 6200w Fedders Ms...     spanish   
27          27  Piedritas Sanitarias Stone Cat X 24kg ¡¡ Aglom...     spanish   
28          28         Arte De Bordar N 5 Alfabetos Em Ponto Cruz  portuguese   
29          29  Mascara Fotosensible Careta Soldar Ploteo Fueg...     spanish   
...        ...                                                ...         ...   
246925  246925                    Bota Industrial Calfor Pampeana     spanish   
246926  246926  Vestido Novia Importado En Encaje Y Chiffon Bl...     spanish   
246927  246927                         Paralama Direito Polo 2008  portuguese   
246928  246928  Indio Gigante Ovos Galados/ferteis A Nossa Duz...  portuguese   
246929  246929  Kit 36 Canudo Longo De Vidro Reutilizável Reto...  portuguese   
246930  246930  Silla Mecedora Bebe Con Vibracion Sonido Jugue...     spanish   
246931  246931  Par Lâmpada Philips Led Fog Ultinon 6200k H8 H...  portuguese   
246932  246932  Inalador Nebulizador Ultrassônico Portatil Pro...  portuguese   
246933  246933  Cinta Correctora Estilo De La Pluma, De Líneas...     spanish   
246934  246934                        Tanque Nafta Corsa Clasicc      spanish   
246935  246935    Contrabaixo Strinberg Cab16 - 4 Cordas Sunburst  portuguese   
246936  246936                 Muy Linda Cinta Athletic A Reparar     spanish   
246937  246937          Portalampara Con Chicote Pack 10 Unidades     spanish   
246938  246938     Revista Formula 1 F1 50 Anos Dourados Raridade  portuguese   
246939  246939     Kit De Bixenon H4 12v 8000k Hid Xenon Kith4-8k     spanish   
246940  246940  Solia De Viraró Seco De Horno De 12mm. De Espesor     spanish   
246941  246941                           Ena Shaker Premium Vaso      spanish   
246942  246942  Interruptor Vidro Traseiro 

In [34]:
df.iloc[49]

id                                                              49
title            Espelho Veneziano Oval Decorativo Retro Vintag...
language                                                portuguese
main_category                             Casa, Moveis e Decoracao
category                                                      BEDS
Name: 49, dtype: object

In [35]:
cat = 'Casa, Moveis e Decoracao'
learn_c = load_learner('/data/anime/ml/por/', cat + '_model_export', test = df[(df.language == 'portuguese') & (df.main_category == cat)])